version: '3.8'

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_HOST=${DATABASE_HOST:-host.docker.internal}
      - DATABASE_PORT=${DATABASE_PORT:-3307}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-mariadb}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-mariadb}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_QUEUE_NAME=${DATABASE_QUEUE_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SELENIUM_REMOTE_URL=http://selenium:4444
      - SOLID_QUEUE_IN_PUMA=1
    networks:
      - shared-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - selenium
    stdin_open: true
    tty: true

  selenium:
    image: selenium/standalone-chromium:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC port pour debug visuel si besoin
    networks:
      - shared-network

volumes:
  bundle_cache:
  node_modules:

networks:
  shared-network:
    external: true
